# Generated by Django 5.0.6 on 2024-12-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
